#!/usr/bin/env bash

# This will flag the workspace as urgent until you switch to it.

parse() {
  case $1 in
	  activewindowv2*) active=$(echo $line | sed 's/activewindowv2>>/0x/')
		  if [ "$active" = "$arg" ]; then echo ""; fi
		  ;;
	  urgent*) arg=$(echo $line | sed 's/urgent>>/0x/')
		  urgent=$(hyprctl clients -j | jq --arg query $arg '.[] | select(.address == $query) | .workspace.id')
		  echo $urgent
		  ;;
  esac
}

# Hyprland version < v0.40.0
# socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do parse "$line"; done

# Hyprland version >= v0.40.0
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do parse "$line"; done
